services:
  - type: web
    name: eazystore-backend
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d2gc1lruibrs73e778mg-a:5432/eazystore?sslmode=require
      - key: DB_USERNAME
        value: eazystore
      - key: DB_PASSWORD
        fromDatabase:
          name: eazystore-db
          property: password
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://eazystore-ui-kanhas-projects-982262fb.vercel.app

databases:
  - name: eazystore-db
    databaseName: eazystore
    user: eazystore
    plan: free