services:
  - type: web
    name: eazystore
    env: java
    plan: free
    region: singapore
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: FRONTEND_URL
        value: https://your-frontend-app.onrender.com  # Update this with your frontend URL
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d2gc1lruibrs73e778mg-a:5432/eazystore?sslmode=require
      - key: DB_USERNAME
        value: eazystore
      - key: DB_PASSWORD
        fromDatabase:
          name: eazystore-db
          property: password
      - key: RAZORPAY_KEY_ID
        sync: false  # You'll need to set this in Render dashboard
      - key: RAZORPAY_KEY_SECRET
        sync: false  # You'll need to set this in Render dashboard
      - key: JPA_SHOW_SQL
        value: "false"
      - key: HIBERNATE_FORMAT_SQL
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"

databases:
  - name: eazystore-db
    databaseName: eazystore
    plan: free  # Free tier for development, upgrade for production
